language: node_js
node_js:
- node
- '6'
- '5.11'
notifications:
  slack:
    rooms:
      secure: rExgSwMdEd8JjVi9JQJ0p1wMKjX4TgNIIg6IDULbMMleIEoNRw8BLzRNVD3sWq1qwqdkLgHHrQEbs10w8jjtlxUA41MuUlWt98ZnkuM1AN9lmZoJSc9zIYQ9MN+tOHidSepe+eweauQeK1K363tkhYDHv+UaHNFYYDwU+/j8qfs2WaJBb+ZUEC51Rq/N/RgYBmBbOdRJjk0GpwyEkzf+vLJg6SiaBf4qXljm+4DDQ3cnMAZ2Xh7JTWuSPGMyotb61pNc0bdfv5jnRsZ7/s7YP0dDqnG2ff39uwlEWO0bhMRZ8E3sKf6SeLEgy6ZFwi5oFGYytYGdfWR7sfA5IXq5L2jtzJM7u1Qhz5Deze+DEnI4aL1VzMhSHOUx9/qv6sev6qMKTGLgnID0WQD5IVqhAPYKLLzQPSqlvbcyeb5iPs84WgqvFYm77AbRuOjIKA/G9HkM9A5oSeRV8eTh3BoB87U7W1blAbZFc8gUL2MUmLPXL1spa9MP7HxItifhbQb2juOqYhvl31O3arfvto8sq1xQ30gsHldeehnM8dk1eRMyVYGaoAAmPfth07GN1iYq+3MiRbHKxAhfA2PN4DanOwdLH3/qwSAg/SXiq/npKldgOm0MhN3kXKX5ReMUd1cQc8Xfz3agAbV67TSoQzUitqApGfb01iRvqvRta+SNXww=
after_success:
  - bash <(curl -s https://codecov.io/bash)