FROM node:6.2.2

MAINTAINER Fusion Alliance <code@fusionalliance.com>

ENV DEBUG=app
ENV HOME=/home/app

RUN mkdir -p $HOME
WORKDIR $HOME

# RUN npm install -g node-gyp parallelshell watch eslint-config-es5 eslint-plugin-import eslint uglifyjs karma karma-mocha karma-chai karma-phantomjs-launcher mocha chai rimraf mkdirp

CMD ["npm", "run", "watch:dev"]
